import 'dart:convert';
import 'dart:io';

void main() {
  // Read the JSON file into a string
  final jsonString = File('assets/images.json').readAsStringSync();

  // Parse the JSON string into a list of maps
  final List<dynamic> cards = jsonDecode(jsonString);

  // Define the category mappings
  var categoryMappings = {
    "Common": [
      "adverb of place",
      "adverb of manner",
      "adverb of degree",
      "adverb of affirmation",
      "qualifying adjective",
      "ordinal adjective",
      "indefinite adjective",
      "demonstrative adjective",
      "possessive adjective",
      "adjective",
      "comparative adjective",
      "language",
      "alphabet",
      "letter",
      "concessive conjunction",
      "copulative conjunction",
      "causal conjunction",
      "adversative conjunction",
      "conditional conjunction",
      "personal pronoun",
      "indefinite pronoun",
      "interrogative pronoun",
      "verb",
      "usual verbs",
      "size",
      "energy",
      "preposition",
      "object",
      "color",
      "number",
      "container",
      "shape",
      "basic concepts",
      "miscellaneous"
    ],
    "Food and Drinks": [
      "beverage",
      "condiment",
      "gastronomy",
      "ultra-processed food",
      "meat",
      "fruit",
      "plant-based food",
      "food",
      "processed food",
      "cold meat",
      "vegetable",
      "dessert",
      "egg product",
      "sweets",
      "dried fruit",
      "spices",
      "baking",
      "traditional dish",
      "mineral rich food",
      "animal-based food",
      "seafood",
      "crustacean",
      "cookery",
      "hunting",
      "animal housing",
      "fishing",
      "dietetics",
      "legume",
      "feeding",
      "dairy product",
    ],
    "Buildings and Infrastructure": [
      "infrastructure",
      "sports facility",
      "building facility",
      "facility",
      "residential building",
      "public building",
      "service building",
      "cultural building",
      "building",
      "building room",
      "industrial building",
      "residential building",
      "commercial building",
      "construction",
      "monument"
    ],
    "People, Communication and Society": [
      "group",
      "elderly",
      "teenager",
      "baby",
      "family",
      "adult",
      "indigenouos people",
      "person according to their age",
      "child",
      "marital status",
      "human response",
      "communication aid",
      "augmentative communication",
      "communication system",
      "social movement",
      "gender identity",
      "human value",
      "expression",
      "polite set expression",
      "bullying",
      "disruptive behavior",
      "students",
      "body position",
      "leader"
    ],
    "Transport": [
      "land transport",
      "aerial transport",
      "water transport",
      "mode of transport",
      "transport services"
    ],
    "Home and Interior Design": [
      "utensil",
      "trousseau",
      "furniture",
      "electrical appliance",
      "crockery",
      "cutlery",
      "decorative item",
      "cleaning product",
      "home",
      "appliance",
      "carpentry",
      "room"
    ],
    "Fashion and Accessories": [
      "clothes",
      "jewelry",
      "footwear",
      "accessories",
      "fashion",
      "sportswear",
      "physical features",
      "cosmetic"
    ],
    "Feelings and Sensations": [
      "taste",
      "body sensation",
      "senses",
      "texture",
      "feeling"
    ],
    "Animals": [
      "arachnid",
      "omnivorous",
      "carnivorous",
      "reptile",
      "mammal",
      "dinosaur",
      "fossil",
      "annelid",
      "marine animal",
      "amphibian",
      "fish-animal",
      "invertebrate animal",
      "aquatic animal",
      "vertebrate",
      "animal anatomy",
      "herbivorous",
      "fish",
      "flying animal",
      "terrestrial animal",
      "extinct being",
      "viviparous",
      "oviparous",
      "animal physiology",
      "animal group",
      "animal reproduction",
      "animal material",
      "dinosaur anatomy",
      "animal",
      "bird",
      "pet",
      "insect",
      "apiculture",
      "coelenterata",
      "mollusc",
      "fossil origin material"
    ],
    "Plants": [
      "tree",
      "flower",
      "bush",
      "herbaceous plant",
      "plant anatomy",
      "plant",
      "fungus",
      "aromatic plant",
      "plant physiology",
      "cactus",
      "forestry",
      "agriculture",
      "cereal",
      "vegetal origin material"
    ],
    "Technology": [
      "mass media device",
      "hardware",
      "computing",
      "information technology",
      "orthographic sign",
      "mass media",
      "multimedia buttons",
      "atmospheric device",
      "music device",
      "chronological device",
      "vehicle component",
      "protective equipment",
      "light fixture"
    ],
    "Science": [
      "geology",
      "meteorology",
      "biology",
      "physiology",
      "chemistry",
      "mathematics",
      "oceanography",
      "physics",
      "geometry",
      "archaeology",
      "psychology",
      "paleontology",
      "environmental science",
      "pollution",
      "astronomy",
      "atmospheric phenomena",
      "measurement unit",
      "planet",
      "natural disaster",
    ],
    "Entertainment and Events": [
      "toy",
      "board game",
      "card game",
      "traditional game",
      "video game",
      "game",
      "olympic games",
      "popular event",
      "event",
      "sport event",
      "social event",
      "chess",
      "bullfighting",
      "photography",
      "recreational facility",
      "entertainment facility",
      "carnival",
      "gambling",
      "popular festival",
      "cinema",
      "wedding",
      "show",
      "opera",
      "hobby",
      "tv show",
      "leisure"
    ],
    "Holidays": [
      "easter week",
      "birthday",
      "christmas",
      "halloween",
      "new year",
      "fiestas del pilar"
    ],
    "Medicine and Health": [
      "physiotherapy",
      "human anatomy",
      "symptom",
      "health personnel",
      "hygiene product",
      "medical procedure",
      "veterinary medicine",
      "healthy habit",
      "addiction",
      "immune system",
      "covid-19",
      "medicine",
      "gynecology",
      "reproductive system",
      "intimate hygiene",
      "drug addiction",
      "smoking",
      "ophthalmology",
      "nervous system",
      "animal-assisted therapy",
      "speech therapy",
      "occupational therapy",
      "physiotherapy equipment",
      "therapy",
      "corporal hygiene",
      "medical device",
      "muscular system",
      "equine-assisted therapy",
      "dog-assisted therapy",
      "alcoholism",
      "medicament",
      "medical center",
      "medical test",
      "medical equipment",
      "medical treatment",
      "medical documentation",
      "medical document",
      "digestive system",
      "circulatory system",
      "excretory system",
      "physiology",
      "disease",
      "sexual practice",
      "health sciences",
      "odontology",
      "sexual orientation",
      "human reproduction",
      "nursing equipment",
      "psychomotor equipment",
      "prevention measure",
      "hospital room",
      "patient",
      "sexuality",
      "contraceptive method",
      "orofacial praxis",
      "sensory stimulation material",
      "obstetrics",
      "basic needs",
      "orthopedic product"
    ],
    "Sports": [
      "diving",
      "karate",
      "swimming",
      "swimming pool",
      "surf",
      "football",
      "horse riding",
      "tourism",
      "cycling",
      "dance",
      "skating",
      "acrobatic gymnastics",
      "physical exercise",
      "adapted sport",
      "sport rules",
      "sport",
      "sport material",
      "athlete",
      "sport modality"
    ],
    "Education": [
      "educational building",
      "educational methodology",
      "subject",
      "educational material",
      "educational task",
      "educational staff",
      "educational equipment",
      "education",
      "special education",
      "education professionals",
      "educational space",
      "educational organization",
      "educational document",
      "educational institution",
      "aac implementation",
      "teaching activity"
    ],
    "History": [
      "late modern period",
      "early modern period",
      "periods",
      "ancient history",
      "history",
      "prehistory",
      "middle ages",
      "iberians",
      "historical character"
    ],
    "Law": [
      "law and justice",
      "crime",
      "sexual crime",
      "gender violence",
      "legal institution",
      "court document",
      "law",
      "trade document",
      "supporting document",
      "information document",
      "document",
      "official document"
    ],
    "Time and Seasons": [
      "day hours",
      "day",
      "day time",
      "unit of time",
      "month",
      "adverb of time",
      "chronological device",
      "calendar",
      "winter",
      "autumn",
      "spring",
      "season"
    ],
    "Religion": [
      "religion",
      "religious character",
      "religious act",
      "religious place",
      "religious event",
      "religious object",
      "religious building",
      "religious person",
      "religion",
      "hinduism",
      "judaism",
      "islamism",
      "buddhism",
      "christianity"
    ],
    "Music": [
      "percussion instrument",
      "wind instrument",
      "string instrument",
      "keyboard instrument",
      "musical instrument",
      "musical art",
      "musical artist",
      "musical notation"
    ],
    "Industries": [
      "industry",
      "hospitality industry",
      "clothing industry",
      "mining industry"
    ],
    "Geography and Countries": [
      "egypt",
      "country",
      "physical geography",
      "natural habitat",
      "political geography",
      "spain province",
      "province",
      "city",
      "river",
      "rural area",
      "urban area",
      "natural habitat",
      "landform",
      "sea and oceans",
      "mountain",
      "spain region",
      "region",
      "regional costume",
      "regional dance",
      "flag",
      "continent"
    ],
    "Politics and Economics": [
      "trade",
      "money",
      "foreign currency",
      "economy",
      "coin",
      "bill",
      "financial services",
      "political representation",
      "election",
      "public administration",
      "international organziation"
    ],
    "Books and Characters": [
      "book character",
      "character",
      "tale character",
      "movie character",
      "mythological character",
      "set phrase",
      "literature",
      "literacy genre",
      "library science",
      "publication",
      "lexicon",
      "article",
      "comic character",
      "universal decimal classification"
    ],
    "Work and Professions": [
      "hairdresser",
      "seller",
      "personal services",
      "sanitary professional",
      "professional services",
      "professional",
      "professional artist",
      "gardening",
      "artist",
      "performing artist",
      "visual artist",
      "work organization",
      "work accident",
      "workwear",
      "work machine",
      "work tool",
      "worksite",
      "workplace",
      "childcare",
      "cattle farming"
    ],
    "Outside": [
      "street furniture",
      "traffic signal",
      "road safety",
      "outdoor activity",
      "signaling system",
      "place",
      "traffic accident",
      "route",
      "catering establishment",
      "beach",
      "movement",
      "sculpture",
      "waste disposal",
      "recycling center",
      "living being",
      "playground",
      "visual art"
    ],
    "No category": [
      "architectural element",
      "recycling",
      "painting",
      "routine",
      "drawing",
      "architecture",
      "raw material",
      "war",
      "communication system",
      "culture",
      "security and defense",
      "categorization",
      "craftsmanship",
      "death",
      "pattern",
      "mineral origin material",
      "weapon",
      "derived material",
      "costume",
      "theater",
      ""
    ]
  };
  // Modify the category of each card based on the category mappings
  for (final card in cards) {
    card.remove("id");
    card['subcategory'] = card['category'];
    for (final category in categoryMappings.keys) {
      if (categoryMappings[category]!.contains(card['category'])) {
        card['category'] = category;
      }
      card["keyword"] = card["keyword"].trim();
    }
  }

  categoryMappings = {
    "Nature": ["Animals", "Plants"],
    "World": ["Politics and Economics", "Law", "Industries"]
  };
  // Modify the category of each card based on the category mappings
  for (final card in cards) {
    card['subcategory'] = card['category'];
    for (final category in categoryMappings.keys) {
      if (categoryMappings[category]!.contains(card['category'])) {
        card['category'] = category;
      }
      card["keyword"] = card["keyword"].trim();
    }
  }

  // Write the modified cards to a JSON file
  final File file = File('assets/grouped.json');
  file.writeAsStringSync(json.encode(cards));
  print(Set.from(cards.map((e) => e["category"])).length);
}

String getCategory(
    Map<dynamic, dynamic> card, Map<String, List<dynamic>> categoryMappings) {
  // Iterate over each category and check if this card belongs to it
  for (final category in categoryMappings.keys) {
    final cardsInCategory = categoryMappings[category];

    if (cardsInCategory!.contains(card['category'])) {
      return category;
    }
  }

  // If the card does not belong to any category, return 'Uncategorized'
  return 'Uncategorized';
}
